name: Secrets Test

on: [push]

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Print secret
      env:
        TB_API: ${{ secrets.TB_API }}
      run: echo "The secret TB_API is: $TB_API"
